name: Extract Links
on:
  push:
    branches:
      - main
jobs:
  extract-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run program
        run: go run main.go
