name: Extract Links
on:
  push:
    branches:
      - main
jobs:
  extract-links:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        #run: go get -v -t -d ./repo
        run: |
          go mod init Go_proxy
          go get golang.org/x/net/html
        
      - name: Run program
        run: go run main.go

