name: Extract Links

on:
  push:
    branches:
      - main
jobs:
  extract-links:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod init Go_proxy
          go get golang.org/x/net/html
      - name: Run program
        run: go run main.go
      - name: Push sub file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ secrets.NAME }}
          author_email: ${{ secrets.EMAIL }}
          message: "Add links.sub"
          add: "links.sub"
          token: ${{ secrets.GITHUB_TOKEN }}

